services:
  pskm.api:
    image: ${DOCKER_REGISTRY-}pskmapi
    build:
      context: .
      dockerfile: PSKM.API/Dockerfile
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080 