services:
  pskm.api:
    image: ${DOCKER_REGISTRY-}pskmapi
    build:
      context: .
      dockerfile: PSKM.API/Dockerfile
    ports:
      - "3000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - "pskmdb"

  pskmdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111021
      - POSTGRES_DB=pgdb
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
